# Generated by Django 3.0.8 on 2020-07-21 14:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('total', models.IntegerField(default=0)),
                ('responsable', models.ForeignKey(default='auth.User', max_length=400, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salidas',
                'verbose_name_plural': 'Salidas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.IntegerField(default=0, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('categoria', models.CharField(choices=[('riester', 'Riester'), ('genericos', 'Genericos'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='DESCRIPCION')),
                ('stockinicial', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('salidas', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m', verbose_name='Imagen')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.Producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.Salida')),
            ],
            options={
                'verbose_name': 'Detalle de Salida',
                'verbose_name_plural': 'Detalle de Salidas',
                'ordering': ['id'],
            },
        ),
    ]
